# Generated by Django 3.0.6 on 2020-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_experience_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(max_length=10055),
        ),
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.FileField(blank=True, upload_to='courses/static'),
        ),
    ]
